version: '3'
services:
  app:
    build: .
    command: ./bin/startup.sh
    volumes:
      - .:/app
      - bundle:/bundle
    env_file:
      - ./.docker/db.env
    ports:
      - '3000:3000'
      - '5000:5000'
    links:
      - db

  db:
    image: sameersbn/postgresql
    ports:
      - 5432
    env_file:
      - ./.docker/db.env
    volumes:
      - postgres:/var/lib/postgresql

volumes:
  bundle:
  postgres:
