default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DB_HOST') %>
  username: <%= ENV.fetch('PG_USER') %>
  password: <%= ENV.fetch('PG_PASSWORD') %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test
